   # CI/CD Workflow 관련 설명 
  
  # 1. Workflow 없으면 모든 작업 수동으로 해야 함
  #    - Gradle 빌드, Docker 이미지 생성, 이미지 push, 서버 배포 등
  #    - 실무에서는 수동 처리 불가능
    
  # 2. Workflow 하나면 자동화 가능
  #    - GitHub Actions Workflow 파일을 통해
  #      → 자동 빌드 (Gradle)
  #      → Docker 이미지 생성
  #      → Docker Hub push
  #      → 서버 배포 준비
    
  # 3. CI/CD 파이프라인의 핵심
  #    - Workflow 파일(.github/workflows/ci-cd.yml)이
  #      프로젝트 자동화의 엔진 역할을 담당
    
  


name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/admin-backoffice:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/admin-backoffice:latest
